// Set curado de emojis para el picker de ícono de documento (~300, agrupados
// por categoría). Sin dependencia externa: la data pesa ~12kb y alcanza para
// documentos de trabajo. `name` mezcla inglés y español para que la búsqueda
// funcione en ambos idiomas (se matchea por substring, case-insensitive).

export type EmojiEntry = { char: string; name: string }
export type EmojiCategoryKey =
  | 'smileys'
  | 'people'
  | 'nature'
  | 'food'
  | 'travel'
  | 'activities'
  | 'objects'
  | 'symbols'
export type EmojiCategory = { key: EmojiCategoryKey; emojis: EmojiEntry[] }

export const EMOJI_CATEGORIES: EmojiCategory[] = [
  {
    key: 'smileys',
    emojis: [
      { char: '😀', name: 'grinning smile sonrisa feliz' },
      { char: '😄', name: 'happy smile eyes feliz risa' },
      { char: '😁', name: 'beaming grin sonriente' },
      { char: '😂', name: 'joy tears laugh risa llorar' },
      { char: '🤣', name: 'rofl laughing carcajada' },
      { char: '😊', name: 'blush smiling sonrojado' },
      { char: '😇', name: 'innocent halo angel santo' },
      { char: '🙂', name: 'slight smile sonrisa leve' },
      { char: '😉', name: 'wink guiño' },
      { char: '😍', name: 'heart eyes love enamorado' },
      { char: '😘', name: 'kiss beso' },
      { char: '😋', name: 'yum tasty rico' },
      { char: '😜', name: 'winking tongue lengua' },
      { char: '🤪', name: 'zany crazy loco' },
      { char: '🤔', name: 'thinking pensando duda' },
      { char: '🤨', name: 'raised eyebrow ceja escéptico' },
      { char: '😐', name: 'neutral face neutro' },
      { char: '😏', name: 'smirk pícaro' },
      { char: '😴', name: 'sleeping dormir sueño' },
      { char: '😪', name: 'sleepy cansado' },
      { char: '😷', name: 'mask médico barbijo' },
      { char: '🤒', name: 'sick fever enfermo fiebre' },
      { char: '🤯', name: 'mind blown explosión cabeza' },
      { char: '😎', name: 'cool sunglasses lentes' },
      { char: '🥳', name: 'party celebración festejo' },
      { char: '😢', name: 'crying sad triste llorar' },
      { char: '😭', name: 'sob loudly crying llanto' },
      { char: '😤', name: 'frustrated triumph frustrado' },
      { char: '😡', name: 'angry rage enojado' },
      { char: '🤬', name: 'cursing swearing puteando' },
      { char: '😱', name: 'scream fear miedo grito' },
      { char: '😨', name: 'fearful asustado' },
      { char: '🥺', name: 'pleading puppy eyes porfa' },
      { char: '🙃', name: 'upside down irony dado vuelta' },
      { char: '🤗', name: 'hug abrazo' },
      { char: '🤫', name: 'shush silence silencio secreto' },
      { char: '🤥', name: 'lying pinocchio mentira' },
      { char: '🫠', name: 'melting derretido' },
      { char: '💀', name: 'skull calavera muerto' },
      { char: '🤖', name: 'robot bot' },
      { char: '👻', name: 'ghost fantasma' },
      { char: '👽', name: 'alien extraterrestre' },
      { char: '🎃', name: 'pumpkin halloween calabaza' },
      { char: '🤡', name: 'clown payaso' },
    ],
  },
  {
    key: 'people',
    emojis: [
      { char: '👋', name: 'wave hello hola saludo mano' },
      { char: '👍', name: 'thumbs up like aprobar pulgar' },
      { char: '👎', name: 'thumbs down dislike rechazar' },
      { char: '👏', name: 'clap applause aplauso' },
      { char: '🙌', name: 'raised hands celebrate manos' },
      { char: '🙏', name: 'pray thanks please gracias rezar' },
      { char: '🤝', name: 'handshake deal acuerdo trato' },
      { char: '💪', name: 'muscle strong fuerza brazo' },
      { char: '👉', name: 'point right señalar derecha' },
      { char: '👈', name: 'point left señalar izquierda' },
      { char: '☝️', name: 'point up arriba índice' },
      { char: '✌️', name: 'victory peace paz' },
      { char: '🤞', name: 'crossed fingers suerte' },
      { char: '✍️', name: 'writing hand escribir' },
      { char: '👀', name: 'eyes look watching ojos mirar' },
      { char: '🧠', name: 'brain cerebro idea mente' },
      { char: '🗣️', name: 'speaking head hablar voz' },
      { char: '👤', name: 'user person silhouette usuario persona' },
      { char: '👥', name: 'users people group usuarios grupo' },
      { char: '🧑‍💻', name: 'developer technologist programador dev' },
      { char: '🧑‍🎨', name: 'artist artista diseño' },
      { char: '🧑‍🔬', name: 'scientist científico laboratorio' },
      { char: '🧑‍🏫', name: 'teacher profesor docente' },
      { char: '🧑‍⚕️', name: 'health worker doctor médico' },
      { char: '🧑‍🍳', name: 'cook chef cocinero' },
      { char: '🧑‍🚀', name: 'astronaut astronauta espacio' },
      { char: '🕵️', name: 'detective spy investigar espía' },
      { char: '👨‍👩‍👧‍👦', name: 'family familia' },
      { char: '🦸', name: 'superhero héroe' },
      { char: '🧙', name: 'wizard mage mago' },
      { char: '👑', name: 'crown king queen corona rey' },
      { char: '🎓', name: 'graduation cap education graduado educación' },
    ],
  },
  {
    key: 'nature',
    emojis: [
      { char: '🐶', name: 'dog puppy perro' },
      { char: '🐱', name: 'cat kitten gato' },
      { char: '🐭', name: 'mouse ratón' },
      { char: '🐰', name: 'rabbit bunny conejo' },
      { char: '🦊', name: 'fox zorro' },
      { char: '🐻', name: 'bear oso' },
      { char: '🐼', name: 'panda' },
      { char: '🐨', name: 'koala' },
      { char: '🦁', name: 'lion león' },
      { char: '🐯', name: 'tiger tigre' },
      { char: '🐮', name: 'cow vaca' },
      { char: '🐷', name: 'pig cerdo chancho' },
      { char: '🐸', name: 'frog rana' },
      { char: '🐵', name: 'monkey mono' },
      { char: '🐔', name: 'chicken gallina pollo' },
      { char: '🐧', name: 'penguin pingüino' },
      { char: '🦅', name: 'eagle águila' },
      { char: '🦉', name: 'owl búho lechuza' },
      { char: '🦄', name: 'unicorn unicornio' },
      { char: '🐝', name: 'bee abeja' },
      { char: '🦋', name: 'butterfly mariposa' },
      { char: '🐌', name: 'snail caracol lento' },
      { char: '🐢', name: 'turtle tortuga' },
      { char: '🐍', name: 'snake serpiente víbora' },
      { char: '🐙', name: 'octopus pulpo' },
      { char: '🦈', name: 'shark tiburón' },
      { char: '🐬', name: 'dolphin delfín' },
      { char: '🐳', name: 'whale ballena' },
      { char: '🐟', name: 'fish pez' },
      { char: '🦖', name: 'dinosaur trex dinosaurio' },
      { char: '🐉', name: 'dragon dragón' },
      { char: '🌵', name: 'cactus' },
      { char: '🌲', name: 'evergreen tree árbol pino' },
      { char: '🌳', name: 'tree árbol' },
      { char: '🍀', name: 'clover luck trébol suerte' },
      { char: '🌿', name: 'herb leaf hoja planta' },
      { char: '🍁', name: 'maple leaf otoño hoja' },
      { char: '🌸', name: 'cherry blossom flor rosa' },
      { char: '🌻', name: 'sunflower girasol' },
      { char: '🌹', name: 'rose rosa flor' },
      { char: '🌷', name: 'tulip tulipán flor' },
      { char: '🍄', name: 'mushroom hongo seta' },
      { char: '🌍', name: 'earth globe world mundo tierra planeta' },
      { char: '🌙', name: 'moon luna noche' },
      { char: '⭐', name: 'star estrella' },
      { char: '🌟', name: 'glowing star brillante estrella' },
      { char: '⚡', name: 'lightning bolt rayo energía' },
      { char: '🔥', name: 'fire flame fuego hot' },
      { char: '🌈', name: 'rainbow arcoíris' },
      { char: '☀️', name: 'sun sol' },
      { char: '☁️', name: 'cloud nube' },
      { char: '🌧️', name: 'rain lluvia' },
      { char: '❄️', name: 'snowflake snow nieve frío' },
      { char: '🌊', name: 'wave ocean ola mar agua' },
      { char: '💧', name: 'drop water gota agua' },
    ],
  },
  {
    key: 'food',
    emojis: [
      { char: '🍎', name: 'apple manzana' },
      { char: '🍌', name: 'banana' },
      { char: '🍇', name: 'grapes uvas' },
      { char: '🍓', name: 'strawberry frutilla fresa' },
      { char: '🍉', name: 'watermelon sandía' },
      { char: '🍋', name: 'lemon limón' },
      { char: '🍑', name: 'peach durazno' },
      { char: '🍍', name: 'pineapple ananá piña' },
      { char: '🥑', name: 'avocado palta aguacate' },
      { char: '🥕', name: 'carrot zanahoria' },
      { char: '🌽', name: 'corn maíz choclo' },
      { char: '🍞', name: 'bread pan' },
      { char: '🧀', name: 'cheese queso' },
      { char: '🥚', name: 'egg huevo' },
      { char: '🥓', name: 'bacon panceta' },
      { char: '🍔', name: 'burger hamburguesa' },
      { char: '🍟', name: 'fries papas fritas' },
      { char: '🍕', name: 'pizza' },
      { char: '🌮', name: 'taco' },
      { char: '🍣', name: 'sushi' },
      { char: '🍜', name: 'ramen noodles fideos sopa' },
      { char: '🍝', name: 'spaghetti pasta' },
      { char: '🥗', name: 'salad ensalada' },
      { char: '🍿', name: 'popcorn pochoclo' },
      { char: '🍦', name: 'ice cream helado' },
      { char: '🍩', name: 'donut dona' },
      { char: '🍪', name: 'cookie galleta' },
      { char: '🎂', name: 'cake birthday torta cumpleaños' },
      { char: '🍫', name: 'chocolate' },
      { char: '🍬', name: 'candy caramelo' },
      { char: '☕', name: 'coffee café' },
      { char: '🍵', name: 'tea té' },
      { char: '🧉', name: 'mate' },
      { char: '🍺', name: 'beer cerveza birra' },
      { char: '🍷', name: 'wine vino' },
      { char: '🥂', name: 'cheers champagne brindis' },
    ],
  },
  {
    key: 'travel',
    emojis: [
      { char: '🚗', name: 'car auto coche' },
      { char: '🚕', name: 'taxi' },
      { char: '🚌', name: 'bus colectivo' },
      { char: '🚑', name: 'ambulance ambulancia' },
      { char: '🚒', name: 'fire truck bomberos' },
      { char: '🚚', name: 'truck delivery camión' },
      { char: '🚜', name: 'tractor' },
      { char: '🏍️', name: 'motorcycle moto' },
      { char: '🚲', name: 'bike bicycle bicicleta' },
      { char: '🛴', name: 'scooter monopatín' },
      { char: '🚆', name: 'train tren' },
      { char: '🚇', name: 'metro subway subte' },
      { char: '✈️', name: 'airplane avión viaje' },
      { char: '🚀', name: 'rocket launch cohete lanzamiento' },
      { char: '🛸', name: 'ufo ovni' },
      { char: '🚁', name: 'helicopter helicóptero' },
      { char: '⛵', name: 'sailboat velero barco' },
      { char: '🚢', name: 'ship barco' },
      { char: '⚓', name: 'anchor ancla' },
      { char: '🗺️', name: 'map mapa' },
      { char: '🧭', name: 'compass brújula' },
      { char: '🏔️', name: 'mountain montaña' },
      { char: '🌋', name: 'volcano volcán' },
      { char: '🏕️', name: 'camping carpa' },
      { char: '🏖️', name: 'beach playa' },
      { char: '🏝️', name: 'island isla' },
      { char: '🏙️', name: 'city ciudad' },
      { char: '🏠', name: 'house home casa' },
      { char: '🏢', name: 'office building oficina edificio' },
      { char: '🏥', name: 'hospital' },
      { char: '🏦', name: 'bank banco' },
      { char: '🏫', name: 'school escuela' },
      { char: '🏰', name: 'castle castillo' },
      { char: '⛪', name: 'church iglesia' },
      { char: '🗽', name: 'statue liberty estatua libertad' },
      { char: '🎡', name: 'ferris wheel vuelta al mundo' },
    ],
  },
  {
    key: 'activities',
    emojis: [
      { char: '⚽', name: 'soccer football fútbol pelota' },
      { char: '🏀', name: 'basketball básquet' },
      { char: '🏈', name: 'american football' },
      { char: '⚾', name: 'baseball béisbol' },
      { char: '🎾', name: 'tennis tenis' },
      { char: '🏐', name: 'volleyball vóley' },
      { char: '🎱', name: 'pool billiards billar bola 8' },
      { char: '🏓', name: 'ping pong tenis de mesa' },
      { char: '🥊', name: 'boxing boxeo guante' },
      { char: '🏋️', name: 'weightlifting pesas gimnasio gym' },
      { char: '🤸', name: 'cartwheel gimnasia' },
      { char: '⛷️', name: 'ski esquí' },
      { char: '🏄', name: 'surf' },
      { char: '🏊', name: 'swim natación nadar' },
      { char: '🧗', name: 'climbing escalada' },
      { char: '🚴', name: 'cycling ciclismo' },
      { char: '🏆', name: 'trophy win campeón trofeo copa' },
      { char: '🥇', name: 'gold medal first medalla oro primero' },
      { char: '🥈', name: 'silver medal second plata segundo' },
      { char: '🥉', name: 'bronze medal third bronce tercero' },
      { char: '🎖️', name: 'military medal medalla' },
      { char: '🎯', name: 'target dart goal objetivo diana' },
      { char: '🎮', name: 'game controller videojuego joystick' },
      { char: '🕹️', name: 'joystick arcade' },
      { char: '🎲', name: 'dice game dado' },
      { char: '♟️', name: 'chess pawn ajedrez' },
      { char: '🧩', name: 'puzzle piece rompecabezas pieza' },
      { char: '🎳', name: 'bowling' },
      { char: '🎣', name: 'fishing pesca' },
      { char: '🎨', name: 'art palette arte pintura diseño' },
      { char: '🎭', name: 'theater drama teatro máscaras' },
      { char: '🎬', name: 'clapper movie cine película' },
      { char: '🎤', name: 'microphone micrófono cantar' },
      { char: '🎧', name: 'headphones auriculares música' },
      { char: '🎸', name: 'guitar guitarra' },
      { char: '🎹', name: 'piano teclado' },
      { char: '🥁', name: 'drum batería tambor' },
      { char: '🎺', name: 'trumpet trompeta' },
      { char: '🎻', name: 'violin violín' },
      { char: '🎵', name: 'music note nota musical' },
      { char: '🎉', name: 'party popper fiesta festejo confeti' },
      { char: '🎊', name: 'confetti ball festejo' },
      { char: '🎁', name: 'gift present regalo' },
      { char: '🎈', name: 'balloon globo' },
    ],
  },
  {
    key: 'objects',
    emojis: [
      { char: '💻', name: 'laptop computer computadora notebook' },
      { char: '🖥️', name: 'desktop computer monitor pc' },
      { char: '⌨️', name: 'keyboard teclado' },
      { char: '🖱️', name: 'mouse ratón' },
      { char: '📱', name: 'phone mobile celular teléfono' },
      { char: '🖨️', name: 'printer impresora' },
      { char: '💾', name: 'floppy save disquete guardar' },
      { char: '💿', name: 'cd disc disco' },
      { char: '📷', name: 'camera cámara foto' },
      { char: '🎥', name: 'video camera filmadora' },
      { char: '📺', name: 'tv television televisión' },
      { char: '📻', name: 'radio' },
      { char: '🎙️', name: 'studio microphone micrófono podcast' },
      { char: '⏰', name: 'alarm clock despertador reloj' },
      { char: '⏱️', name: 'stopwatch cronómetro' },
      { char: '⌛', name: 'hourglass reloj de arena tiempo' },
      { char: '🔋', name: 'battery batería pila' },
      { char: '🔌', name: 'plug enchufe' },
      { char: '💡', name: 'light bulb idea lamparita foco' },
      { char: '🔦', name: 'flashlight linterna' },
      { char: '🕯️', name: 'candle vela' },
      { char: '🧯', name: 'fire extinguisher matafuegos extintor' },
      { char: '💰', name: 'money bag dinero plata bolsa' },
      { char: '💵', name: 'dollar bill billete dólar' },
      { char: '💳', name: 'credit card tarjeta crédito' },
      { char: '💎', name: 'gem diamond diamante gema' },
      { char: '⚖️', name: 'balance scale justicia balanza legal' },
      { char: '🔧', name: 'wrench tool llave herramienta' },
      { char: '🔨', name: 'hammer martillo' },
      { char: '⚙️', name: 'gear settings engranaje config' },
      { char: '🧲', name: 'magnet imán' },
      { char: '🧪', name: 'test tube experiment tubo ensayo química' },
      { char: '🧬', name: 'dna adn genética' },
      { char: '🔬', name: 'microscope microscopio' },
      { char: '🔭', name: 'telescope telescopio' },
      { char: '💊', name: 'pill medicine pastilla remedio' },
      { char: '💉', name: 'syringe jeringa vacuna' },
      { char: '🚪', name: 'door puerta' },
      { char: '🪑', name: 'chair silla' },
      { char: '🛒', name: 'shopping cart carrito compras' },
      { char: '📦', name: 'package box paquete caja' },
      { char: '✉️', name: 'envelope mail sobre correo' },
      { char: '📧', name: 'email correo' },
      { char: '📝', name: 'memo note nota apunte escribir' },
      { char: '📄', name: 'page document página documento' },
      { char: '📋', name: 'clipboard portapapeles lista' },
      { char: '📅', name: 'calendar calendario fecha' },
      { char: '📊', name: 'bar chart gráfico barras estadística' },
      { char: '📈', name: 'chart up growth gráfico subida crecimiento' },
      { char: '📉', name: 'chart down gráfico bajada caída' },
      { char: '📌', name: 'pushpin pin chinche' },
      { char: '📎', name: 'paperclip clip' },
      { char: '✂️', name: 'scissors tijera cortar' },
      { char: '🖊️', name: 'pen lapicera birome' },
      { char: '✏️', name: 'pencil lápiz' },
      { char: '🖍️', name: 'crayon' },
      { char: '🖌️', name: 'paintbrush pincel' },
      { char: '📚', name: 'books libros estudio' },
      { char: '📖', name: 'open book libro abierto leer' },
      { char: '📓', name: 'notebook cuaderno' },
      { char: '🗂️', name: 'card index dividers archivo carpetas' },
      { char: '📁', name: 'folder carpeta' },
      { char: '🗄️', name: 'file cabinet archivero' },
      { char: '🗑️', name: 'wastebasket trash basura papelera' },
      { char: '🔒', name: 'lock locked candado seguridad' },
      { char: '🔓', name: 'unlock abierto' },
      { char: '🔑', name: 'key llave' },
      { char: '🗝️', name: 'old key llave antigua' },
      { char: '🛡️', name: 'shield escudo seguridad defensa' },
      { char: '⚔️', name: 'crossed swords espadas combate' },
      { char: '🗡️', name: 'dagger sword espada daga' },
      { char: '🏹', name: 'bow arrow arco flecha' },
      { char: '🔮', name: 'crystal ball bola cristal magia' },
      { char: '🧸', name: 'teddy bear peluche oso' },
      { char: '🎀', name: 'ribbon bow moño lazo' },
      { char: '🔔', name: 'bell campana notificación' },
      { char: '📢', name: 'loudspeaker announcement anuncio megáfono' },
      { char: '🔍', name: 'magnifying glass search lupa buscar' },
      { char: '🧹', name: 'broom escoba limpieza' },
      { char: '🧺', name: 'basket canasta' },
    ],
  },
  {
    key: 'symbols',
    emojis: [
      { char: '❤️', name: 'red heart corazón rojo amor' },
      { char: '🧡', name: 'orange heart corazón naranja' },
      { char: '💛', name: 'yellow heart corazón amarillo' },
      { char: '💚', name: 'green heart corazón verde' },
      { char: '💙', name: 'blue heart corazón azul' },
      { char: '💜', name: 'purple heart corazón violeta' },
      { char: '🖤', name: 'black heart corazón negro' },
      { char: '💔', name: 'broken heart corazón roto' },
      { char: '💯', name: 'hundred perfect cien puntos' },
      { char: '✅', name: 'check mark done listo tilde verde ok' },
      { char: '☑️', name: 'checkbox casilla tilde' },
      { char: '✔️', name: 'check tilde ok' },
      { char: '❌', name: 'cross x error mal rojo' },
      { char: '❗', name: 'exclamation important importante signo' },
      { char: '❓', name: 'question pregunta duda signo' },
      { char: '⚠️', name: 'warning cuidado advertencia alerta' },
      { char: '🚫', name: 'prohibited no prohibido' },
      { char: '♻️', name: 'recycle reciclar' },
      { char: '🔴', name: 'red circle círculo rojo' },
      { char: '🟠', name: 'orange circle círculo naranja' },
      { char: '🟡', name: 'yellow circle círculo amarillo' },
      { char: '🟢', name: 'green circle círculo verde' },
      { char: '🔵', name: 'blue circle círculo azul' },
      { char: '🟣', name: 'purple circle círculo violeta' },
      { char: '⚫', name: 'black circle círculo negro' },
      { char: '⚪', name: 'white circle círculo blanco' },
      { char: '🟥', name: 'red square cuadrado rojo' },
      { char: '🟩', name: 'green square cuadrado verde' },
      { char: '🟦', name: 'blue square cuadrado azul' },
      { char: '➡️', name: 'arrow right flecha derecha' },
      { char: '⬅️', name: 'arrow left flecha izquierda' },
      { char: '⬆️', name: 'arrow up flecha arriba' },
      { char: '⬇️', name: 'arrow down flecha abajo' },
      { char: '🔄', name: 'refresh cycle actualizar ciclo' },
      { char: '🔁', name: 'repeat loop repetir' },
      { char: '➕', name: 'plus add más sumar' },
      { char: '➖', name: 'minus menos restar' },
      { char: '➗', name: 'divide división' },
      { char: '✖️', name: 'multiply multiplicar por' },
      { char: '♾️', name: 'infinity infinito' },
      { char: '💲', name: 'dollar sign signo pesos' },
      { char: '©️', name: 'copyright' },
      { char: '™️', name: 'trademark marca' },
      { char: '🔞', name: 'adults only mayores 18' },
      { char: '📴', name: 'phone off apagado' },
      { char: '🆗', name: 'ok button botón' },
      { char: '🆕', name: 'new nuevo' },
      { char: '🆓', name: 'free gratis' },
      { char: '🔝', name: 'top arriba' },
      { char: '🔜', name: 'soon pronto' },
      { char: '#️⃣', name: 'hashtag numeral' },
      { char: '*️⃣', name: 'asterisk asterisco' },
      { char: '0️⃣', name: 'zero cero' },
      { char: '1️⃣', name: 'one uno' },
      { char: '2️⃣', name: 'two dos' },
      { char: '3️⃣', name: 'three tres' },
    ],
  },
]
